1 html
askoptev/html-css-homework pull request #1
Opened 2024-10-08 19:16 UTC by askoptev

2024-10-09 19:24 UTC, Levitinn requested changes

2024-10-09 19:24 UTC, Levitinn commented on 1-Blog/index.html
> +				<li>Мой блог</li>
это должно быть ссылками, вложенными в li

2024-10-09 19:24 UTC, Levitinn commented on 1-Blog/index.html
> +        	<input type="text" placeholder="Поиск" />
все инпуты стоит оборачивать в отдельные дивы. так их будет проще стилизовать

2024-10-09 20:32 UTC, askoptev commented on 1-Blog/index.html
> +        	<input type="text" placeholder="Поиск" />
А в форме, во-втором файле, тоже все input оборачивать в индивидуальные div или можно так и оставить?

2024-10-10 19:16 UTC, Levitinn approved these changes

2024-10-10 19:25 UTC, merged