4 final
askoptev/html-css-homework pull request #5
Opened 2024-11-05 10:53 UTC by askoptev

2024-11-07 19:19 UTC, Levitinn requested changes

2024-11-07 19:19 UTC, Levitinn commented on 4-Finio/index.html
> +      <div class="container header__container">
![image](https://github.com/user-attachments/assets/bb05021a-3058-47da-9d8b-438007346e6c)
это не паддинг контейнера, а хедера

2024-11-07 19:19 UTC, Levitinn commented on 4-Finio/index.html
> +        <a class="logo header__logo" href="#">FINIO</a>
у лого тоже никаких марджинов быть не должно, это паддинг хедера должен быть

2024-11-07 19:19 UTC, Levitinn commented on 4-Finio/index.html
> +          <ul class="menu">
у меню есть базовые браузерные стили. все базовые стили, не только у меню, нужно занулить
![image](https://github.com/user-attachments/assets/4815681b-45d7-4dae-a843-e27b975f584b)

2024-11-07 19:19 UTC, Levitinn commented on 4-Finio/styles/hero.css
> +  margin-bottom: 147px;
если ты хочешь задать какому то элементу паддинг или марджин больше 100, скорее всего ты допускаешь ошибку. Если речь идет об отступах между секциями - ок, во всех остальных случаев, нужно придумать другое решение. в данном случае, это паддинг секции. у контейнера могут быть стили только ограничение по ширине с помощью max-width, width: 100% и выравнивание по центру с помощью margin: 0 auto;
больше ничего.здесь и везде по  странице исправь стили контейнеров

2024-11-07 19:19 UTC, Levitinn commented on 4-Finio/index.html
> +              <img
у всех картинок на странице не заданы максимальные размеры. нужно задать ВСЕМ. напоминаю, что размеры мы даем диву-обертке картинки. а сам имг просто растягивает width: 100%; height:  100%

2024-11-10 18:54 UTC, askoptev commented on 4-Finio/index.html
> +      <div class="container header__container">
![image](https://github.com/user-attachments/assets/9d37e767-2d8c-495b-887d-7a006026d3f1)
Исправил

2024-11-10 18:57 UTC, askoptev commented on 4-Finio/index.html
> +        <a class="logo header__logo" href="#">FINIO</a>
![Снимок экрана_20241110_215542](https://github.com/user-attachments/assets/91d1973a-6b27-4375-9a6f-246f10a05b16)

2024-11-10 18:59 UTC, askoptev commented on 4-Finio/index.html
> +          <ul class="menu">
![Uploading image.png…]()

2024-11-10 18:59 UTC, askoptev commented on 4-Finio/index.html
> +          <ul class="menu">
![image](https://github.com/user-attachments/assets/de09962a-17ee-4ede-9be9-93466657b7a3)

2024-11-10 19:00 UTC, askoptev commented on 4-Finio/styles/hero.css
> +  margin-bottom: 147px;
![image](https://github.com/user-attachments/assets/cba62307-4e53-4b35-80e3-05aaf1d632f1)

2024-11-10 19:02 UTC, askoptev commented on 4-Finio/index.html
> +              <img
![image](https://github.com/user-attachments/assets/ce755851-385b-433b-86f6-ab0f8b8f4e0f)

2024-11-11 19:23 UTC, Levitinn requested changes

2024-11-11 19:23 UTC, Levitinn commented on 4-Finio/styles/global.css
> +  height: 100%;
это грубая ошибка. для боди не нужно давать ни ширину, ни высоту

2024-11-11 19:23 UTC, Levitinn commented on 4-Finio/index.html
> +              <img
высоту забыл. одной ширины недостачно

2024-11-11 20:19 UTC, askoptev commented on 4-Finio/styles/global.css
> +  height: 100%;
![image](https://github.com/user-attachments/assets/ee44c185-103f-4e76-bda9-b5070a31ed89)
Устранил

2024-11-12 19:29 UTC, Levitinn approved these changes

2024-11-30 06:56 UTC, merged